// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            int32       `json:"id"`
	Email         pgtype.Text `json:"email"`
	FullName      pgtype.Text `json:"full_name"`
	Password      pgtype.Text `json:"password"`
	EmailVerified pgtype.Text `json:"email_verified"`
	CreatedAt     time.Time   `json:"created_at"`
}
